{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "So Yummy API",
    "description": "So Yummy API documentation",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://yummy-service.onrender.com" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Recipes",
      "description": "Recipes endpoints"
    },
    {
      "name": "Ingredients",
      "description": "Ingredients endpoints"
    }
  ],
  "paths": {
    "/users/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful registration",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Um, something is missing. Please provide all the requested fields.."
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Oops... Provided email is already in use"
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Um, something is missing. Please provide all the requested fields.."
              }
            }
          },
          "401": {
            "description": "Invalid email or password",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful logout",
            "content": {}
          },
          "401": {
            "description": "Authenticate error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is embarrassing... Sorry, but it seems that you are not authorized person"
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Get current user",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authenticated",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/recipes/category-list": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get list of categories",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryListResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/recipes/categories/{category}": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get list of recipes by category name",
        "security": [{ "Bearer": [] }],
        "params": { "in": "path", "name": "category" },
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryRecipesResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/recipes/{id}": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get a recipes by id",
        "security": [{ "Bearer": [] }],
        "params": { "in": "path", "name": "id" },
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    },
    "/ingredients/list": {
      "get": {
        "tags": ["Ingredients"],
        "summary": "Get list of ingredients",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IngredientsListResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "type": "string",
                "example": "Well, this is unexpected... Sorry, this is not working properly. We now know about this mistake and are working to fix it."
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's email",
            "example": "Kevin K"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "code": {
            "type": "number",
            "description": "Code",
            "example": "201"
          },
          "message": {
            "type": "string",
            "description": "Message",
            "example": "success"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "description": "User's id"
              },
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "password": {
                "type": "string",
                "description": "User's password"
              },
              "subscription": {
                "type": "boolean",
                "description": "User's subscription status",
                "example": false
              },
              "avatarUrl": {
                "type": "string",
                "description": "User's avatar"
              },
              "favorite": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "recipeId": {
                      "type": "string"
                    }
                  }
                }
              },
              "shoppingList": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "recipeId": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "example": {
          "code": "201",
          "message": "success",
          "user": {
            "id": "64ad646ba17ba61a08fd0931",
            "name": "Nato",
            "email": "nato@test.com",
            "subscription": false,
            "avatarUrl": "//www.gravatar.com/avatar/8dc60c9240259bffc7e943a49247a6fa"
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "number",
            "description": "Code",
            "example": 200
          },
          "message": {
            "type": "string",
            "description": "Message",
            "example": "success"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "description": "User's id"
              },
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "password": {
                "type": "string",
                "description": "User's password"
              },
              "subscription": {
                "type": "boolean",
                "description": "User's subscription status",
                "example": false
              },
              "avatarUrl": {
                "type": "string",
                "description": "User's avatar"
              },
              "token": {
                "type": "string",
                "description": "User's token"
              }
            }
          }
        },
        "example": {
          "code": "200",
          "message": "success",
          "user": {
            "id": "64ad646ba17ba61a08fd0931",
            "name": "Nato",
            "email": "nato@test.com",
            "subscription": false,
            "avatarUrl": "//www.gravatar.com/avatar/8dc60c9240259bffc7e943a49247a6fa",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YWQ2NDZiYTE3YmE2MWEwOGZkMDkzMSIsImlhdCI6MTY4OTA4NzI0MSwiZXhwIjoxNjg5MTcwMDQxfQ.ZkZJOEKCqAU-rSkQpgETjvF7xNIDQGyLQ1VnLVy7WQo"
          }
        }
      },
      "CategoryListResponse": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": [
          "Beef",
          "Breakfast",
          "Chicken",
          "Dessert",
          "Goat",
          "Lamb",
          "Miscellaneous",
          "Pasta",
          "Pork",
          "Seafood",
          "Side",
          "Soup",
          "Starter",
          "Vegan",
          "Vegetarian"
        ]
      },
      "CategoryRecipesResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "A recipe's id"
            },
            "title": {
              "type": "string",
              "description": "A title of the recipe",
              "example": "Battenberg Cake"
            },
            "category": {
              "type": "string",
              "description": "Category title",
              "example": "Dessert"
            },
            "area": {
              "type": "string",
              "description": "A country or a region",
              "example": "British"
            },
            "instructions": {
              "type": "string",
              "description": "Instruction for cooking"
            },
            "description": {
              "type": "string",
              "description": "A description for a meal",
              "example": "A classic British cake..."
            },
            "thumb": {
              "type": "string",
              "description": "Thumb's link"
            },
            "preview": {
              "type": "string",
              "description": "Preview image link"
            },
            "time": {
              "type": "string",
              "description": "Time for cooking",
              "example": "60"
            },
            "youtube": {
              "type": "string",
              "description": "Youtube link"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "example": ["Cake", "Sweet"]
            },
            "ingredients": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "Ingredient's id"
                  },
                  "measure": {
                    "type": "string",
                    "description": "Ingedient measure",
                    "example": "175g"
                  }
                }
              }
            }
          },
          "example": [
            {
              "_id": "6462a8f74c3d0ddd28897fcd",
              "title": "Battenberg Cake",
              "category": "Dessert",
              "area": "British",
              "instructions": "Heat oven to 180C/160C fan/gas 4 and line the base and sides of a 20cm square tin with baking parchment (the easiest way is to cross 2 x 20cm-long strips over the base). To make the almond sponge, put the butter, sugar, flour, ground almonds, baking powder, eggs, vanilla and almond extract in a large bowl. Beat with an electric whisk until the mix comes together smoothly. Scrape into the tin, spreading to the corners, and bake for 25-30 mins – when you poke in a skewer, it should come out clean. Cool in the tin for 10 mins, then transfer to a wire rack to finish cooling while you make the second sponge",
              "description": "A classic British cake made with almond sponge cake and covered with marzipan. It is traditionally pink and yellow checkered in appearance.",
              "thumb": "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg",
              "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560624/fxkadubcfpgqtacvvgbl.jpg",
              "time": "60",
              "youtube": "https://www.youtube.com/watch?v=aB41Q7kDZQ0",
              "tags": ["Cake", "Sweet"],
              "ingredients": [
                {
                  "id": "640c2dd963a319ea671e367e",
                  "measure": "175g"
                },
                {
                  "id": "640c2dd963a319ea671e3687",
                  "measure": "175g"
                }
              ]
            },
            {
              "_id": "6462a8f74c3d0ddd28897fcc",
              "title": "Blackberry Fool",
              "category": "Dessert",
              "area": "British",
              "instructions": "For the biscuits, preheat the oven to 200C/180C (fan)/Gas 6 and line two large baking trays with baking parchment. Scatter the nuts over a baking tray and roast in the oven for 6-8 minutes, or until golden-brown. Watch them carefully so that they don’t have a chance to burn.",
              "description": "A light and creamy dessert made with whipped cream and blackberries, perfect for summer.",
              "thumb": "https://www.themealdb.com/images/media/meals/rpvptu1511641092.jpg",
              "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560630/udf2g6mv8gm0eqvqylha.jpg",
              "time": "60",
              "youtube": "https://www.youtube.com/watch?v=kniRGjDLFrQ",
              "tags": ["Desert", "Summer", "Fruity", "Dairy"],
              "ingredients": [
                {
                  "id": "640c2dd963a319ea671e380c",
                  "measure": "50g"
                },
                {
                  "id": "640c2dd963a319ea671e367e",
                  "measure": "125g"
                }
              ]
            }
          ]
        }
      },
      "RecipeResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "A recipe id"
          },
          "title": {
            "type": "string",
            "description": "A title of the recipe",
            "example": "Battenberg Cake"
          },
          "category": {
            "type": "string",
            "description": "Category title",
            "example": "Dessert"
          },
          "area": {
            "type": "string",
            "description": "A country or a region",
            "example": "British"
          },
          "instructions": {
            "type": "string",
            "description": "Instruction for cooking"
          },
          "description": {
            "type": "string",
            "description": "A description for a meal",
            "example": "A classic British cake..."
          },
          "thumb": {
            "type": "string",
            "description": "Thumb link"
          },
          "preview": {
            "type": "string",
            "description": "Preview image link"
          },
          "time": {
            "type": "string",
            "description": "Time for cooking",
            "example": "60"
          },
          "youtube": {
            "type": "string",
            "description": "Youtube link"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": ["Cake", "Sweet"]
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Ingradient id"
                },
                "measure": {
                  "type": "string",
                  "description": "Ingradient measure",
                  "example": "175g"
                }
              }
            }
          }
        },
        "example": {
          "_id": "6462a8f74c3d0ddd28897fcd",
          "title": "Battenberg Cake",
          "category": "Dessert",
          "area": "British",
          "instructions": "Heat oven to 180C/160C fan/gas 4 and line the base and sides of a 20cm square tin with baking parchment (the easiest way is to cross 2 x 20cm-long strips over the base). To make the almond sponge, put the butter, sugar, flour, ground almonds, baking powder, eggs, vanilla and almond extract in a large bowl. Beat with an electric whisk until the mix comes together smoothly. Scrape into the tin, spreading to the corners, and bake for 25-30 mins – when you poke in a skewer, it should come out clean. Cool in the tin for 10 mins, then transfer to a wire rack to finish cooling while you make the second sponge",
          "description": "A classic British cake made with almond sponge cake and covered with marzipan. It is traditionally pink and yellow checkered in appearance.",
          "thumb": "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg",
          "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560624/fxkadubcfpgqtacvvgbl.jpg",
          "time": "60",
          "youtube": "https://www.youtube.com/watch?v=aB41Q7kDZQ0",
          "tags": ["Cake", "Sweet"],
          "ingredients": [
            {
              "id": "640c2dd963a319ea671e367e",
              "measure": "175g"
            },
            {
              "id": "640c2dd963a319ea671e3687",
              "measure": "175g"
            }
          ]
        }
      },
      "IngredientsListResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Ingredient's id"
            },
            "name": {
              "type": "string",
              "description": "Ingredient's name"
            },
            "desc": {
              "type": "string",
              "description": "Ingredient's description"
            },
            "image": {
              "type": "string",
              "description": "Ingredient's image link"
            }
          },
          "example": [
            {
              "_id": "640c2dd963a319ea671e366c",
              "name": "Beef Brisket",
              "desc": "Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times. Beef is a source of high-quality protein and nutrients.\r\n\r\nMost beef skeletal muscle meat can be used as is by merely cutting into certain parts, such as roasts, short ribs or steak (filet mignon, sirloin steak, rump steak, rib steak, rib eye steak, hanger steak, etc.), while other cuts are processed (corned beef or beef jerky). Trimmings, on the other hand, are usually mixed with meat from older, leaner (therefore tougher) cattle, are ground, minced or used in sausages. The blood is used in some varieties called blood sausage. Other parts that are eaten include other muscles and offal, such as the oxtail, liver, tongue, tripe from the reticulum or rumen, glands (particularly the pancreas and thymus, referred to as sweetbread), the heart, the brain (although forbidden where there is a danger of bovine spongiform encephalopathy, BSE, commonly referred to as mad cow disease), the kidneys, and the tender testicles of the bull (known in the United States as calf fries, prairie oysters, or Rocky Mountain oysters). Some intestines are cooked and eaten as is, but are more often cleaned and used as natural sausage casings. The bones are used for making beef stock.",
              "img": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564216/piozjulqxuluu25jrlws.png"
            },
            {
              "_id": "640c2dd963a319ea671e3667",
              "name": "Basil",
              "desc": "Basil, also called great basil, is a culinary herb of the family Lamiaceae (mints).\r\n\r\nBasil is native to tropical regions from central Africa to Southeast Asia. It is a tender plant, and is used in cuisines worldwide. Depending on the species and cultivar, the leaves may taste somewhat like anise, with a strong, pungent, often sweet smell.",
              "img": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564215/jpmvh7yslyxzie8gihi1.png"
            }
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
